title: "Machine Learning Ops"
description: "Community Driven tools for Machine Learning Operations."
url: "https://machine-learning-apps.github.io/MLOps/"
twitter:
  username: github

repository: machine-learning-apps/MLOps

markdown: kramdown
exclude:
  - readme.md
  - Rakefile
  - script
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
  - "package.json"
  - node_modules
  - .bundle
  - ".ruby-version"
  - ".gitignore"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

sass:
  # Where you keep your scss files
  sass_dir: css/

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "document"
