name: Build Pages
on:
  push:
    branches:
      - master

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: setup directories for Jekyll build
      run: |
        cd site
        rm -rf _site
        sudo chmod -R 777 .
        
    - name: Jekyll build
      uses: docker://jekyll/jekyll
      with:
        args: /bin/bash -c "cd site; bundle install --binstubs bin --path vendor/gems; bundle exec jekyll build $@"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_DIR: ./site/_site
        PUBLISH_BRANCH: gh-pages
