name: Build Pages
on:
  push:
    branches:
      - master

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: setup directories for Jekyll build
      run: |
        cd site
        rm -rf _site
        sudo chmod -R 777 .
        
    - name: Jekyll build
      uses: docker://jekyll/jekyll
      with:
        args: /bin/bash -c "chmod 755 /usr/gem/cache; cd site; bundle install -—binstubs; bundle exec jekyll build"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./site/_site
        keep_files: false
